# .github/workflows/ci_pipeline.yml
name: CI Pipeline - Parcial Backend

# Esto le dice a GitHub que se active cuando hagas un push a la rama main o master
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Usaremos una máquina Linux virtual de GitHub

    steps:
    # 1. Descargar tu código en la máquina virtual
    - name: Checkout del código
      uses: actions/checkout@v3

    # 2. Instalar Python
    - name: Configurar Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Instalar las librerías que pusimos en requirements.txt
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Ejecutar las pruebas (Pytest)
    # Si esto falla, GitHub te marcará una X roja. Si pasa, un check verde.
    - name: Correr Pruebas
      run: |
        pytest